### ISSUE TITLE
Report on Continuous Replication job doesn't show VM info

### ISSUE THREAD

**Issue by Danp2** [vatesfr/xo-server-backup-reports#3] opened 2016-02-12 01:35 UTC
This is what shows in the report:
```
VM : undefined
UUID: undefined 
```
Is there a valid reason for the line `vm = this._xo.getObject(call.params.id)` failing on a CR job?

**Comment by olivierlambert** [comment] 2016-02-12 08:06
Calling @Wescoeur or @julien-f

**Comment by julien-f** [comment] 2016-02-12 08:07
Yes, because the parameter is named `vm` instead of `id`, our API is far from being homogeneous (which is something we are planning to work on, because the API will be documented to be used directly by customers :)).

I merged your PR without proper validation because it could not introduce regressions, I will fix your case very soon :)

**Comment by julien-f** [comment] 2016-02-12 08:10
I just pushed a fix, feel free to reopen if you get the same problem, or open a new one if another problem occur :)

**Closed** 2016-02-12 08:09 UTC
